# Generated by Django 5.1.5 on 2025-02-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sproutapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='content_id',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
