# Generated by Django 5.1.5 on 2025-02-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sproutapp', '0002_rename_content_id_activity_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
