# Generated by Django 5.1.5 on 2025-02-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sproutapp', '0003_alter_user_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
